// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgo2ugJfzcB_1fdLUkE32ia_mAgNrMAg0',
    appId: '1:382209190088:web:60023c652388504cd3ddfd',
    messagingSenderId: '382209190088',
    projectId: 'sornaplo-7c388',
    authDomain: 'sornaplo-7c388.firebaseapp.com',
    storageBucket: 'sornaplo-7c388.appspot.com',
    measurementId: 'G-GY689ECPB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlB6aOuDuTqalSMmftCj0nOURllyuJUmA',
    appId: '1:382209190088:android:bc68c6e8ff8d403fd3ddfd',
    messagingSenderId: '382209190088',
    projectId: 'sornaplo-7c388',
    storageBucket: 'sornaplo-7c388.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5PvggDuWFz2edBGHD1jloE6qOfPC5liA',
    appId: '1:382209190088:ios:95432a143a57ddb6d3ddfd',
    messagingSenderId: '382209190088',
    projectId: 'sornaplo-7c388',
    storageBucket: 'sornaplo-7c388.appspot.com',
    iosClientId: '382209190088-813vr3eo00ivrd7vthgd2kb8uinosa7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.sornaplo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5PvggDuWFz2edBGHD1jloE6qOfPC5liA',
    appId: '1:382209190088:ios:107031e9586f2593d3ddfd',
    messagingSenderId: '382209190088',
    projectId: 'sornaplo-7c388',
    storageBucket: 'sornaplo-7c388.appspot.com',
    iosClientId: '382209190088-qfi4m819qs5boft0hgqtp4abasmkc2i3.apps.googleusercontent.com',
    iosBundleId: 'com.example.sornaplo.RunnerTests',
  );
}
